name: "02 - terraform apply to: sandbox"

on:
  pull_request:
    types:
      - closed
    branches:
      - 'sandbox'

env:
  TF_CLOUD_ORGANIZATION: "deploymenttheory"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "terraform-jamfpro-sandbox"
  CONFIG_DIRECTORY: "workload/terraform/jamfpro"
  PIPELINE_DEBUG: true

permissions:
  pull-requests: write  # required to update PR
  contents: write       # required to create release and branch
  id-token: write 

jobs:
  terraform-apply:
    if: github.event.pull_request.merged == true
    name: "Terraform Apply to Sandbox"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        
      - name: Harden Runner
        uses: step-security/harden-runner@v2.9.1
        with:
          egress-policy: audit

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.1
        id: apply-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Create Terraform Apply Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.1
        id: apply-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}

      - name: Terraform Apply
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.1
        if: fromJSON(steps.apply-run.outputs.payload).data.attributes.actions.IsConfirmable
        id: apply
        with:
          run: ${{ steps.apply-run.outputs.run_id }}
          comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"

      - name: Set up Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: '1.23.1'
  
      - name: Get Apply Results
        env:
          TF_RUN_ID: ${{ steps.apply-run.outputs.run_id }}
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          TF_WORKSPACE: ${{ env.TF_WORKSPACE }}
          TF_CLOUD_ORGANIZATION: ${{ env.TF_CLOUD_ORGANIZATION }}
        run: |
          cd workload/scripts/get_apply_results
          go build -o get_apply_results
          ./get_apply_results > ../../../apply_results.json
        working-directory: ${{ github.workspace }}

      - name: Update PR
        if: github.event.pull_request.merged == true
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const applyResults = JSON.parse(fs.readFileSync('apply_results.json', 'utf8'));
            
            let output = `#### Terraform Apply Result 🚀\n\n`;
            output += `**Status:** ${applyResults.status}\n\n`;
            output += `**Resources Added:** ${applyResults.resources_added}\n`;
            output += `**Resources Changed:** ${applyResults.resources_changed}\n`;
            output += `**Resources Destroyed:** ${applyResults.resources_destroyed}\n\n`;
            output += `[View Run Details](${applyResults.run_url})\n\n`;
            output += `*Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });